# Generated by Django 3.1.2 on 2020-10-21 13:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20201020_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
